import Link from 'next/link'

export const metadata = {
  title: 'Terms & Conditions | Chulbuli Jewels',
  description: 'Terms and conditions for using Chulbuli Jewels website and services in accordance with Indian law.',
}

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-champagne via-pearl to-champagne py-16">
      {/* Header */}
      <div className="max-w-4xl mx-auto px-8 md:px-16">
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-playfair text-warmbrown mb-4 tracking-wide">
            Terms & Conditions
          </h1>
          <div className="h-px w-32 bg-gradient-to-r from-transparent via-rosegold to-transparent mx-auto mb-6" />
          <p className="text-warmbrown/80 text-lg font-light">
            Please read these terms carefully before using our services
          </p>
          <p className="text-warmbrown/60 text-sm mt-2">Last Updated: February 6, 2026</p>
        </div>

        {/* Important Notice */}
        <div className="mb-12 bg-amber-50 border-l-4 border-rosegold p-6 rounded-r-lg shadow-md">
          <p className="text-warmbrown font-semibold mb-2 uppercase tracking-wide text-sm">Important Notice</p>
          <p className="text-warmbrown/80 text-sm leading-relaxed">
            By accessing, browsing or otherwise using the Platform, you indicate your agreement to all the terms and conditions under these Terms of Use. Please read these terms carefully before proceeding.
          </p>
        </div>

        {/* Detailed Terms */}
        <div className="bg-white/70 backdrop-blur-sm rounded-lg p-8 md:p-12 shadow-luxury border border-rosegold/20 space-y-8">
          
          <section>
            <h2 className="font-playfair text-2xl text-warmbrown mb-4 flex items-center gap-3">
              <div className="h-px flex-1 bg-gradient-to-r from-rosegold/50 to-transparent" />
              Electronic Record & Legal Compliance
              <div className="h-px flex-1 bg-gradient-to-l from-rosegold/50 to-transparent" />
            </h2>
            <div className="space-y-3 text-warmbrown/80 text-sm md:text-base leading-relaxed">
              <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
              <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://www.chulbulijewels.in (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).</p>
            </div>
          </section>

          <div className="h-px bg-gradient-to-r from-transparent via-rosegold/30 to-transparent" />

          <section>
            <h2 className="font-playfair text-2xl text-warmbrown mb-4 flex items-center gap-3">
              <div className="h-px flex-1 bg-gradient-to-r from-rosegold/50 to-transparent" />
              Platform Owner
              <div className="h-px flex-1 bg-gradient-to-l from-rosegold/50 to-transparent" />
            </h2>
            <div className="space-y-3 text-warmbrown/80 text-sm md:text-base leading-relaxed">
              <p>The Platform is owned by <strong className="text-warmbrown">CHULBULI JEWELS</strong>, a company incorporated under the Companies Act, 1956 with its registered office at:</p>
              <div className="bg-rosegold/5 border border-rosegold/30 rounded-lg p-6 mt-4">
                <p className="font-semibold text-warmbrown">Registered Office:</p>
                <p className="mt-2">C 1004 Block C Sahitya Green</p>
                <p>Madhavpura Bapod</p>
                <p>Vadodara, Gujarat 390019</p>
                <p>India</p>
              </div>
              <p className="mt-4">(Hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).</p>
            </div>
          </section>

          <div className="h-px bg-gradient-to-r from-transparent via-rosegold/30 to-transparent" />

          <section>
            <h2 className="font-playfair text-2xl text-warmbrown mb-4 flex items-center gap-3">
              <div className="h-px flex-1 bg-gradient-to-r from-rosegold/50 to-transparent" />
              Scope & Applicability
              <div className="h-px flex-1 bg-gradient-to-l from-rosegold/50 to-transparent" />
            </h2>
            <div className="space-y-3 text-warmbrown/80 text-sm md:text-base leading-relaxed">
              <p>Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction.</p>
              <p>By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, &apos;Services&apos;).</p>
              <p>Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect.</p>
              <p className="font-semibold text-warmbrown">These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.</p>
            </div>
          </section>

          <div className="h-px bg-gradient-to-r from-transparent via-rosegold/30 to-transparent" />

          <section>
            <h2 className="font-playfair text-2xl text-warmbrown mb-4 flex items-center gap-3">
              <div className="h-px flex-1 bg-gradient-to-r from-rosegold/50 to-transparent" />
              Definitions
              <div className="h-px flex-1 bg-gradient-to-l from-rosegold/50 to-transparent" />
            </h2>
            <div className="space-y-3 text-warmbrown/80 text-sm md:text-base leading-relaxed">
              <p>For the purpose of these Terms of Use, wherever the context so requires:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 mt-4">
                <li><strong className="text-warmbrown">&apos;You&apos;, &apos;Your&apos; or &apos;User&apos;</strong> shall mean any natural or legal person who has agreed to become a user/buyer on the Platform</li>
                <li><strong className="text-warmbrown">&apos;Platform&apos;</strong> refers to https://www.chulbulijewels.in, including the related mobile site and mobile application</li>
                <li><strong className="text-warmbrown">&apos;Services&apos;</strong> collectively refers to any services provided through our website, goods or services</li>
              </ul>
            </div>
          </section>

          <div className="h-px bg-gradient-to-r from-transparent via-rosegold/30 to-transparent" />

          <section className="bg-gradient-to-br from-rosegold/10 to-softgold/10 rounded-lg p-6 border border-rosegold/30">
            <p className="text-warmbrown font-bold text-center text-lg mb-2 uppercase tracking-wide">
              Agreement to Terms
            </p>
            <p className="text-warmbrown/80 text-center text-sm md:text-base">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
            </p>
          </section>

          <div className="h-px bg-gradient-to-r from-transparent via-rosegold/30 to-transparent" />

          <section>
            <h2 className="font-playfair text-2xl text-warmbrown mb-4 flex items-center gap-3">
              <div className="h-px flex-1 bg-gradient-to-r from-rosegold/50 to-transparent" />
              Terms of Use
              <div className="h-px flex-1 bg-gradient-to-l from-rosegold/50 to-transparent" />
            </h2>
            <div className="space-y-5 text-warmbrown/80 text-sm md:text-base leading-relaxed">
              <p className="font-semibold text-warmbrown">The use of Platform and/or availing of our Services is subject to the following Terms of Use:</p>
              
              <div className="space-y-4">
                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">1.</span>
                  <p>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">2.</span>
                  <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">3.</span>
                  <p>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">4.</span>
                  <p>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">5.</span>
                  <p>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">6.</span>
                  <p>You agree to pay us the charges associated with availing the Services.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">7.</span>
                  <p>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">8.</span>
                  <p>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">9.</span>
                  <p>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">10.</span>
                  <p>You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">11.</span>
                  <p>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">12.</span>
                  <p>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">13.</span>
                  <p>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Vadodara, Gujarat.</p>
                </div>

                <div className="flex gap-4">
                  <span className="font-bold text-rosegold flex-shrink-0">14.</span>
                  <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
                </div>
              </div>
            </div>
          </section>

          <div className="h-px bg-gradient-to-r from-transparent via-rosegold/30 to-transparent" />

          <section>
            <h2 className="font-playfair text-2xl text-warmbrown mb-4 flex items-center gap-3">
              <div className="h-px flex-1 bg-gradient-to-r from-rosegold/50 to-transparent" />
              Contact Information
              <div className="h-px flex-1 bg-gradient-to-l from-rosegold/50 to-transparent" />
            </h2>
            <div className="space-y-3 text-warmbrown/80 text-sm md:text-base leading-relaxed">
              <p>For questions or concerns regarding these Terms and Conditions, please contact us:</p>
              <div className="bg-rosegold/5 border border-rosegold/30 rounded-lg p-6 mt-4">
                <p><strong className="text-warmbrown">CHULBULI JEWELS</strong></p>
                <p className="mt-3"><strong>Registered Office:</strong></p>
                <p>C 1004 Block C Sahitya Green, Madhavpura Bapod</p>
                <p>Vadodara, Gujarat 390019, India</p>
                <p className="mt-3"><strong>Email:</strong> support@chulbulijewels.in</p>
                <p><strong>Phone:</strong> +91 9867732204</p>
                <p><strong>WhatsApp:</strong> <a href="https://whatsapp.com/channel/0029Vb7CuMe9MF8tE3LGor3R" className="text-rosegold hover:underline" target="_blank" rel="noopener noreferrer">Join our channel</a></p>
                <p><strong>Facebook:</strong> <a href="https://www.facebook.com/profile.php?id=61587171489601" className="text-rosegold hover:underline" target="_blank" rel="noopener noreferrer">Visit our page</a></p>
              </div>
            </div>
          </section>

          <div className="h-px bg-gradient-to-r from-transparent via-rosegold/30 to-transparent" />

          <section className="bg-gradient-to-br from-rosegold/10 to-softgold/10 rounded-lg p-6 border border-rosegold/30">
            <p className="text-warmbrown/80 text-center text-sm md:text-base leading-relaxed">
              <strong className="text-warmbrown">By using Chulbuli Jewels services, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions in accordance with the laws of India.</strong>
            </p>
          </section>
        </div>

        {/* Related Links */}
        <div className="mt-12 grid grid-cols-1 md:grid-cols-4 gap-4">
          <Link
            href="/privacy"
            className="text-center px-6 py-3 bg-white/70 text-warmbrown rounded-full hover:bg-rosegold/10 transition-all duration-300 border border-rosegold/20"
          >
            Privacy Policy
          </Link>
          <Link
            href="/returns"
            className="text-center px-6 py-3 bg-white/70 text-warmbrown rounded-full hover:bg-rosegold/10 transition-all duration-300 border border-rosegold/20"
          >
            Return Policy
          </Link>
          <Link
            href="/shipping"
            className="text-center px-6 py-3 bg-white/70 text-warmbrown rounded-full hover:bg-rosegold/10 transition-all duration-300 border border-rosegold/20"
          >
            Shipping Policy
          </Link>
          <a
            href="/Policies.pdf"
            download
            className="text-center px-6 py-3 bg-rosegold/10 text-warmbrown rounded-full hover:bg-rosegold/20 transition-all duration-300 border border-rosegold/30"
          >
            Download PDF
          </a>
        </div>

        {/* Back Button */}
        <div className="mt-12 text-center">
          <Link
            href="/"
            className="inline-block px-8 py-3 bg-rosegold text-pearl rounded-full hover:bg-rosegold/90 transition-all duration-500 hover:shadow-lg hover:shadow-rosegold/30"
          >
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  )
}
